# CMAKE generated file: DO NOT EDIT!
# Generated by "MinGW Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

SHELL = cmd.exe

# The CMake executable.
CMAKE_COMMAND = "C:\Program Files (x86)\CMake\bin\cmake.exe"

# The command to remove a file.
RM = "C:\Program Files (x86)\CMake\bin\cmake.exe" -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = C:\Users\cl0udman\workspace\mandelbrotSetViewer

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = C:\Users\cl0udman\workspace\mandelbrotSetViewer

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	"C:\Program Files (x86)\CMake\bin\cmake-gui.exe" -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	"C:\Program Files (x86)\CMake\bin\cmake.exe" -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start C:\Users\cl0udman\workspace\mandelbrotSetViewer\CMakeFiles C:\Users\cl0udman\workspace\mandelbrotSetViewer\CMakeFiles\progress.marks
	$(MAKE) -f CMakeFiles\Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start C:\Users\cl0udman\workspace\mandelbrotSetViewer\CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles\Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Mandelbrot

# Build rule for target.
Mandelbrot: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 Mandelbrot
.PHONY : Mandelbrot

# fast build rule for target.
Mandelbrot/fast:
	$(MAKE) -f CMakeFiles\Mandelbrot.dir\build.make CMakeFiles/Mandelbrot.dir/build
.PHONY : Mandelbrot/fast

#=============================================================================
# Target rules for targets named glfw

# Build rule for target.
glfw: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 glfw
.PHONY : glfw

# fast build rule for target.
glfw/fast:
	$(MAKE) -f lib\glfw\src\CMakeFiles\glfw.dir\build.make lib/glfw/src/CMakeFiles/glfw.dir/build
.PHONY : glfw/fast

src/mandelbrot.obj: src/mandelbrot.c.obj

.PHONY : src/mandelbrot.obj

# target to build an object file
src/mandelbrot.c.obj:
	$(MAKE) -f CMakeFiles\Mandelbrot.dir\build.make CMakeFiles/Mandelbrot.dir/src/mandelbrot.c.obj
.PHONY : src/mandelbrot.c.obj

src/mandelbrot.i: src/mandelbrot.c.i

.PHONY : src/mandelbrot.i

# target to preprocess a source file
src/mandelbrot.c.i:
	$(MAKE) -f CMakeFiles\Mandelbrot.dir\build.make CMakeFiles/Mandelbrot.dir/src/mandelbrot.c.i
.PHONY : src/mandelbrot.c.i

src/mandelbrot.s: src/mandelbrot.c.s

.PHONY : src/mandelbrot.s

# target to generate assembly for a file
src/mandelbrot.c.s:
	$(MAKE) -f CMakeFiles\Mandelbrot.dir\build.make CMakeFiles/Mandelbrot.dir/src/mandelbrot.c.s
.PHONY : src/mandelbrot.c.s

# Help Target
help:
	@echo The following are some of the valid targets for this Makefile:
	@echo ... all (the default if no target is provided)
	@echo ... clean
	@echo ... depend
	@echo ... Mandelbrot
	@echo ... edit_cache
	@echo ... rebuild_cache
	@echo ... glfw
	@echo ... src/mandelbrot.obj
	@echo ... src/mandelbrot.i
	@echo ... src/mandelbrot.s
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 0
.PHONY : cmake_check_build_system

